api:
  dashboard: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  ssh:
    address: ":2025"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/config/
    watch: true
#uncomment if not using own certificate
#certificatesResolvers:
#  http:
#    acme:
#      email: email@exemple.net
#      storage: acme.json
#      httpChallenge:
#        entryPoint: http
